spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_db
    username: beny_admin
    password: beny_admin_database_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect