server.port: 8086
spring.application.name=prescription-service
spring.datasource.url=jdbc:postgresql://postgres:5432/hoptal
spring.datasource.username=beny_admin
spring.datasource.password=beny_admin_database_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
medical-record-service.url=http://medical-record-service:8083